stack_name: testsporepaas2-preprod
environment: preproduction
paas_environment: production

layers:
  - dns:
      - name: 'testsporepaas2.preprod.paas.aws.vodafone.com.au'
    instances:
      ami_name: <%=ami_name%>
      env:
        LOG_FILENAME: testsporepaas2-preprod
